name: miauff
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/docation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^1.0.6
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  google_sign_in: ^5.0.2
  curved_navigation_bar: ^0.3.3
  image_picker: ^0.7.4
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: MADE Evolve Sans Regular EVO
      fonts:
        - asset: fonts/MADE Evolve Sans Regular EVO.otf

    - family: Midazzle Demo Outline
      fonts:
        - asset: fonts/Midazzle Demo Outline.ttf

    - family: Manrope Light
      fonts:
        - asset: fonts/Manrope-Light.otf

    - family: Manrope Thin
      fonts:
        - asset: fonts/Manrope-Thin.otf

